MovieSavedApp/Controllers/FiltrosController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using MovieSavedApp.Models;

namespace MovieSavedApp.Controllers
{
    public class FiltrosController : Controller
    {
        MovieSavedDbContext db = new MovieSavedDbContext();

        // GET: Filtros
        public ActionResult FiltroGenero(string genero)
        {
            if ((Session["LogedUserId"]) != null)
            {
                var id_User = (Session["LogedUserId"]);
                var logedUser = Convert.ToInt32(id_User);
                var generoFiltro = db.Genres.Single(u=>u.Name.Equals(genero));


                var relacionpeliculasporusuario = db.MoviesUsers.Where(u=>u.User_Id == logedUser);
                List<Movie>peliculasporusuario = new List<Movie>();

                foreach(var relacion in relacionpeliculasporusuario)
                {
                    peliculasporusuario.Add(db.Movies.Single(u=>u.MovieId==relacion.Movie_Id));  
                }

                List<MovieGenre>relacionusuariogenero = new List<MovieGenre>();

                foreach (var movie in peliculasporusuario)
                {
                    foreach (var relaciongenero in movie.MoviesGenres)
                    { 
                          relacionusuariogenero.Add(relaciongenero);
                    }
                }

                var peliculaGeneroFiltro = relacionusuariogenero.Where(u => u.Genre_Id == generoFiltro.GenreId);
                var peliculasfiltradas = peliculaGeneroFiltro.Select(u=>u.Movie).ToList();


                return View(peliculasfiltradas);
            }
            return RedirectToAction("RegistroIngreso", "Inicio");    
         }
    }
}

MovieSavedApp/Controllers/HomeController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using MovieSavedApp.Models;

namespace MovieSavedApp.Controllers
{
    public class HomeController : Controller
    {
        MovieSavedDbContext db = new MovieSavedDbContext();

        public ActionResult VistaTabla()
        {
            if ((Session["LogedUserId"]) != null)
            {
                var id_User = (Session["LogedUserId"]);
                var logedUser = Convert.ToInt32(id_User);
                var listaRelacionMovieUser = db.MoviesUsers.Where(u => u.User_Id == logedUser);
                //var peliculasUsuario = listaRelacionMovieUser.Select(u => u.Movie).ToList();
                return View(listaRelacionMovieUser);
            }
            return RedirectToAction("RegistroIngreso", "Inicio");
        }

        public ActionResult VistaPoster()
        {
            if ((Session["LogedUserId"]) != null)
            { 
                var id_User = (Session["LogedUserId"]);
                var logedUser = Convert.ToInt32(id_User);
                var listaRelacionMovieUser = db.MoviesUsers.Where(u => u.User_Id == logedUser);
                var peliculasUsuario = listaRelacionMovieUser.Select(u => u.Movie).ToList();
                return View(peliculasUsuario);
            }
            return RedirectToAction("RegistroIngreso", "Inicio");
        }

        [ChildActionOnly]
        public ActionResult GeneroMenu()
        {
            var id_User = (Session["LogedUserId"]);
            var logedUser = Convert.ToInt32(id_User);
            var generos = db.Genres.ToList();

            var relacionpeliculasporusuario = db.MoviesUsers.Where(u=>u.User_Id == logedUser);
            List<Movie>peliculasporusuario = new List<Movie>();

            foreach(var relacion in relacionpeliculasporusuario)
            {
               peliculasporusuario.Add(db.Movies.Single(u=>u.MovieId==relacion.Movie_Id));  
            }

            List<MovieGenre>relacionusuariogenero = new List<MovieGenre>();

            foreach (var movie in peliculasporusuario)
            {
                foreach (var relaciongenero in movie.MoviesGenres) { 
                    relacionusuariogenero.Add(relaciongenero);
                }
            }
            return PartialView(relacionusuariogenero);
        }
    }
}

MovieSavedApp/Views/Home/GeneroMenu.cshtml
@model IEnumerable<MovieSavedApp.Models.MovieGenre>

<ul class="lista-generos">
    @foreach (var genero in Model.Select(u=>u.Genre).Distinct().ToList())
    {
        int conteo = 0;
        conteo = Model.Where(u => u.Genre_Id == genero.GenreId).ToList().Count();
        <li>
            @Html.ActionLink(genero.Name,"FiltroGenero","Filtros", new {genero = genero.Name }, null)
            
            <span id="ConteoGeneroPelicula">
              (@conteo)
            </span>
        </li>
    }
</ul>

MovieSavedApp/Views/Home/Index.cshtml
<div class="jumbotron">
    <h1>ASP.NET</h1>
    <p class="lead">ASP.NET is a free web framework for building great Web sites and Web applications using HTML, CSS, and JavaScript.</p>
    <p><a href="http://asp.net" class="btn btn-primary btn-lg">Learn more &raquo;</a></p>
</div>
<div class="row">
    <div class="col-md-4">
        <h2>Getting started</h2>
        <p>ASP.NET Web API is a framework that makes it easy to build HTTP services that reach
        a broad range of clients, including browsers and mobile devices. ASP.NET Web API
        is an ideal platform for building RESTful applications on the .NET Framework.</p>
        <p><a class="btn btn-default" href="http://go.microsoft.com/fwlink/?LinkId=301870">Learn more &raquo;</a></p>
    </div>
    <div class="col-md-4">
        <h2>Get more libraries</h2>
        <p>NuGet is a free Visual Studio extension that makes it easy to add, remove, and update libraries and tools in Visual Studio projects.</p>
        <p><a class="btn btn-default" href="http://go.microsoft.com/fwlink/?LinkId=301871">Learn more &raquo;</a></p>
    </div>
    <div class="col-md-4">
        <h2>Web Hosting</h2>
        <p>You can easily find a web hosting company that offers the right mix of features and price for your applications.</p>
        <p><a class="btn btn-default" href="http://go.microsoft.com/fwlink/?LinkId=301872">Learn more &raquo;</a></p>
    </div>
</div>

MovieSavedApp/Views/Home/VistaPoster.cshtml
@model IEnumerable<MovieSavedApp.Models.Movie>

@{
    ViewBag.Title = "VistaPoster";
    Layout = "~/Views/Shared/_LayoutPage2.cshtml";
}

<section class="contenido-encabezado">
    <div class="input-group btnSearch" id="boton-busqueda">
        <input type="text" name="table_search" class="form-control input-sm" placeholder="Buscar" />
        <div class="input-group-btn">
            <button class="btn btn-sm btn-default "><i class="fa fa-search "></i></button>
        </div>
    </div>
    <div class="input-group" id="cambio-modovista">
        <a href="@Url.Action("VistaTabla", "Home")" class="btn btn-default"><i class="fa fa-star"></i> Cambiar a vista de tabla</a>
    </div>
</section>
<section class="panel-peliculas ">
    <div class="row">
        <div class="col-xs-12">
            <ul id="lista-cuadricula">
                @foreach (var pelicula in Model.ToList())
                {
                    <li class="cuadro-pelicula">
                        <a href="@Url.Action("Detalles", new {id = pelicula.MovieId})">
                            <div>
                                <div class="poster">
                                    <img alt="poster not found" src="@pelicula.PosterUrl" id="imagen">
                                </div>
                                <div class="texto-pelicula">
                                    <h6><strong>@pelicula.Title</strong><br/><strong>(@pelicula.Year)</strong></h6>
                                </div>
                            </div>
                        </a>
                    </li>
                }
            </ul>
        </div>
    </div>
</section>





    

MovieSavedApp/Views/Home/VistaTabla.cshtml
@model IEnumerable<MovieSavedApp.Models.MovieUser>


@{
    ViewBag.Title = "VistaPoster";
    Layout = "~/Views/Shared/_LayoutPage2.cshtml";
}


     <section class="contenido-encabezado">
          <div class="input-group btnSearch" id="boton-busqueda">
               <input type="text" name="table_search" class="form-control input-sm" placeholder="Buscar" />
               <div class="input-group-btn">
                   <button class="btn btn-sm btn-default "><i class="fa fa-search "></i></button>
               </div>
          </div>
          <div class="input-group" id="cambio-modovista">
                <a href="@Url.Action("VistaPoster", "Home")" class="btn btn-default"><i class="fa fa-star"></i> Cambiar a vista de Posters</a>
          </div>
     </section>
     <section class="panel-peliculas ">
          <div class="row">
              <div class="col-xs-12">
                   <table class="table table-hover">
                       <tr>
                            <th>Título</th>
                            <th>Año</th>
                            <th>Directores</th>
                            <th>País</th>
                            <th>Géneros</th>
                            <th>Tipo de almacenamiento</th>
                            <th>&nbsp;</th>
                       </tr>
                       @foreach (var item in Model)
                       {
                            <tr>
                                <td>
                                    @Html.DisplayFor(modelItem => item.Movie.Title)
                                </td>
                                <td>
                                    @Html.DisplayFor(modelItem => item.Movie.Year)
                                </td>
                                <td>
                                    @foreach (var movieDirector in item.Movie.MoviesDirectors)
                                    {
                                        @movieDirector.Director.Name<span>, </span>
                                    }
                                </td>
                                <td>
                                    @foreach (var moviePais in item.Movie.MoviesCountries)
                                    {
                                        @moviePais.Country.Name<span>, </span>
                                    }
                                </td>
                                <td>
                                    @foreach (var movieGenero in item.Movie.MoviesGenres)
                                    {
                                        @movieGenero.Genre.Name<span>, </span>
                                    }
                                </td>
                                <td>
                                     @foreach (var storage in item.MoviesUsersTypeStorages)
                                    {@storage.TypeStorage.TypeStorageName <span>,</span>}
                                </td>
                                <td>
                                    <a href="@Url.Action("Edit", "Peliculas",new {id = item.Movie.MovieId})"><i class="fa fa-fw fa-edit"></i></a>
                                    <a href="@Url.Action("Delete", "Peliculas",new {id = item.Movie.MovieId})"><i class="fa fa-fw fa-times"></i></a>
                                </td>
                            </tr>
                          }
                    </table>
                </div>
           </div>  
     </section>


        
       