MovieSavedApp/Controllers/InicioController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using MovieSavedApp.Models;

namespace MovieSavedApp.Controllers
{
    public class InicioController : Controller
    {

        // GET: Inicio
        public ActionResult RegistroIngreso()
        {
            return View();
        }

        [HttpPost]
        public ActionResult RegistroIngreso(UserViewModel userView)
        {
            using (MovieSavedDbContext db = new MovieSavedDbContext())
            {
                if (ModelState.IsValid)
                {
                    User newUser = new User();
                    newUser.Username = userView.Username;
                    newUser.Email = userView.Email;
                    newUser.Password = userView.Password;
                    db.Users.Add(newUser);
                    db.SaveChanges();
                }
                ModelState.Clear();
                ViewBag.Message = userView.Username + " se ha registrado exitosamente";
            }
            return View();
        }

        
       
        [ValidateAntiForgeryToken]
        public ActionResult Ingreso(User user)
        {
            if (ModelState.IsValid)
            {
                try
                {
                    using (MovieSavedDbContext db = new MovieSavedDbContext())
                    {
                        var usr = db.Users.Where(a => a.Username.Equals(user.Username) && a.Password.Equals(user.Password)).FirstOrDefault();
                        if (usr != null)
                        {
                            Session["LogedUserId"] = usr.UserId.ToString();
                            Session["LogedUsername"] = usr.Username.ToString();
                            return RedirectToAction("VistaPoster", "Home");
                        }
                        else
                        {
                            ModelState.AddModelError("keyName", "El usuario o la contraseña es incorrecta");
                            return View("RegistroIngreso");
                        }
                    }
                }
                catch (Exception ex)
                {
                    ModelState.AddModelError("KeyName", ex.Message);
                    return View("RegistroIngreso");
                }

            }
            return View();
        }

        public ActionResult Salir()
        {
            Session.Abandon();

            //FormsAuthentication.SignOut();
            return RedirectToAction("RegistroIngreso");
        }

    }
}

MovieSavedApp/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width" />
    <title>@ViewBag.Title</title>
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")
</head>
<body>
    <div class="navbar navbar-inverse navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                @Html.ActionLink("Application name", "Index", "Home", new { area = "" }, new { @class = "navbar-brand" })
            </div>
            <div class="navbar-collapse collapse">
                <ul class="nav navbar-nav">
                    <li>@Html.ActionLink("Home", "Index", "Home", new { area = "" }, null)</li>
                    <li>@Html.ActionLink("API", "Index", "Help", new { area = "" }, null)</li>
                </ul>
            </div>
        </div>
    </div>
    <div class="container body-content">
        @RenderBody()
        <hr />
        <footer>
            <p>&copy; @DateTime.Now.Year - My ASP.NET Application</p>
        </footer>
    </div>

    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/bootstrap")
    @RenderSection("scripts", required: false)
</body>
</html>

MovieSavedApp/Views/Shared/_LayoutPage1.cshtml
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta content='width=device-width, initial-scale=1, maximum-scale=1, user-scalable=no' name='viewport'>
    <title>@ViewBag.Title</title>
    @Styles.Render("~/Content/css")
    @Styles.Render("~/Content/themes/base/css")
    @Styles.Render("~/Content/font-awesome.min.css")
    @Styles.Render("~/Content/ionicons.min.css")
    @Styles.Render("~/Content/datepicker3.css")
    @Styles.Render("~/Content/daterangepicker-bs3.css")
    @Styles.Render("~/Content/bootstrap3-wysihtml5.min.css")
    @Scripts.Render("~/bundles/modernizr")
    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/bootstrap")
    @Scripts.Render("~/bundles/jqueryval")
    @Scripts.Render("~/bundles/site")
    <link href='http://fonts.googleapis.com/css?family=Paytone+One' rel='stylesheet' type='text/css'>
</head>

<body>
    <!-- Logo -->
    <header>
        <section class="BarraEncabezado">
            <span id="TituloPagina">
                MOVIESAVED
            </span>
        </section>
        <section class="BarraMenu bg-blue-gradient ">
            <ul class="ul-MenuDerecho">
                <li class="active">
                    <a href="@Url.Action("Index", "Home")">
                        <span>Acerca de nosotros&nbsp;&nbsp;</span>
                    </a>
                </li>
                <li class="active">
                    <a href="@Url.Action("Index", "Home")">
                        <span>Contacto&nbsp;&nbsp;</span>
                    </a>
                </li>
                <li class="active">
                    <a href="@Url.Action("Index", "Home")">
                        <span>Ayuda&nbsp;&nbsp;</span>
                    </a>
                </li>
            </ul>
        </section>
    </header>
    @RenderBody()
    <hr />
    <footer>
        <p>&copy; @DateTime.Now.Year - Hernando Delgado - Juan Acosta</p>
    </footer>
</body>
</html>

MovieSavedApp/Views/Shared/_LayoutPage2.cshtml
@{
    ViewBag.Title = "Home";
}

<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta content='width=device-width, initial-scale=1, maximum-scale=1, user-scalable=no' name='viewport'>
    <title>@ViewBag.Title</title>
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")
    @Styles.Render("~/Content/themes/base/css")
    @Styles.Render("~/Content/font-awesome.min.css")
    @Styles.Render("~/Content/ionicons.min.css")
    @Styles.Render("~/Content/datepicker3.css")
    @Styles.Render("~/Content/daterangepicker-bs3.css")
    @Styles.Render("~/Content/bootstrap3-wysihtml5.min.css")
    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/bootstrap")
    @Scripts.Render("~/bundles/jqueryval")
    @Scripts.Render("~/bundles/site")


    <link href='http://fonts.googleapis.com/css?family=Paytone+One' rel='stylesheet' type='text/css'>
</head>

<body>
    <!-- Logo -->
    <header>
        <section class="BarraEncabezado">
            <span id="TituloPagina">
                MOVIESAVED
            </span>
            <div class="nombre-usuario ">
                <i class="glyphicon glyphicon-user"> </i>
                <span id="texto-usuario">Usuario:  @Session["LogedUsername"].ToString()</span>
            </div>
        </section>
        <section class="BarraMenu bg-blue-gradient ">
            <ul class="ul-MenuDerecho">
                <li class="active">
                    <a href="@Url.Action("Salir", "Inicio")">
                        <span>Salir&nbsp;|&nbsp;</span>
                    </a>
                </li>
                <li class="active">
                    <a href="@Url.Action("Index", "Home")">
                        <span>Acerca de nosotros&nbsp;|&nbsp;</span>
                    </a>
                </li>
                <li class="active">
                    <a href="@Url.Action("Index", "Home")">
                        <span>Contacto&nbsp;|&nbsp;</span>
                    </a>
                </li>
                <li class="active">
                    <a href="@Url.Action("Index", "Home")">
                        <span>Ayuda&nbsp;|&nbsp;</span>
                    </a>
                </li>
            </ul>
            <ul class="ul-MenuIzquierdo">
                <li class="active">
                    <a href="@Url.Action("Index", "Home")">
                        <span>&nbsp;&nbsp;Home</span>
                    </a>
                </li>
                <li class="active">
                    <a href="@Url.Action("Index", "Home")">
                        <span>&nbsp;|&nbsp;Buscar película en IMDB</span>
                    </a>
                </li>
            </ul>
        </section>
    </header>
    <section class="wrapper row-offcanvas row-offcanvas-left" style="min-height:1200px;">
        <aside class="lado-izquierdo">
            @RenderBody()
        </aside>
        <aside class="lado-derecho sidebar-offcanvas ">
            <section class="panel-filtros">
                <div class="content-header bg-blue-gradient">Filtros flexibles</div>
                <form action="index.html" method="post" class="filtros-body">
                    <div>
                        <div class="form-group">
                            <label>Pais</label>
                            <div class="input-group">
                                <input type="text" name="Pais" class="form-control" />
                            </div>
                        </div>
                        <div class="form-group">
                            <label>Genero</label>
                            <div class="input-group">
                                <input type="text" name="Pais" class="form-control" />
                            </div>
                        </div>
                        <div class="form-group">
                            <label>Director</label>
                            <div class="input-group">
                                <input type="text" name="Pais" class="form-control" />
                            </div>
                        </div>
                        <div class="form-group">
                            <label>Actor</label>
                            <div class="input-group">
                                <input type="text" name="Pais" class="form-control" />
                            </div>
                        </div>
                        <div class="row">
                            <div class="form-group col-xs-6 ">
                                <label>Año</label>
                                <div class="input-group">
                                    <input type="text" name="Nombre" class="form-control" style="margin-right:2.5px" />
                                </div>
                            </div>
                            <div class="form-group col-xs-6">
                                <label>Calificación</label>
                                <div class="input-group">
                                    <input type="text" name="Nombre" class="form-control" style="margin-left:2.5px" />
                                </div>
                            </div>
                        </div>
                        <div class="form-group">
                            <div class="input-group">
                                <button type="submit" class="btn bg-blue btn-block">Filtrar</button>
                            </div>
                        </div>
                    </div>
                </form>
            </section>  
            <section class="panel-generos">
                @{Html.RenderAction("GeneroMenu", "Home");}
            </section>
         </aside>
    </section>

    @Scripts.Render("~/bundles/daterangepicker.js")
    @Scripts.Render("~/bundles/bootstrap-datepicker.js")
    @Scripts.Render("~/bundles/bootstrap3-wysihtml5.all.min.js")
    @Scripts.Render("~/bundles/icheck.min.js")
    @Scripts.Render("~/bundles/app.js")
    @Scripts.Render("~/bundles/dashboard.js")
    @Scripts.Render("~/bundles/demo.js")
    <hr />
    <footer>
        <p>&copy; @DateTime.Now.Year - Hernando Delgado - Juan Acosta</p>
    </footer>
</body>

</html>